// <auto-generated />
namespace Exame_EpNor_2019.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class newdata24 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newdata24));
        
        string IMigrationMetadata.Id
        {
            get { return "201901302247111_newdata24"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
